#!/usr/bin/env python3
"""
DWM1000 Antenna Delay Calibration — Post-Processing
====================================================

Reads CSV output from cal_initiator serial log, computes the
per-device antenna delay correction, and recommends register values.

Usage:
    python3 cal_postprocess.py calibration_data.csv

    Or paste CSV data into a file manually from serial monitor.

The CSV must have this header (generated by cal_initiator.ino):
    sample,millis,distance_m,round_trip_ticks,reply_delay_ticks,
    tof_ticks,rx_power_dBm,fp_power_dBm,quality,
    temp_C,humidity_pct,pressure_hPa

Lines starting with '#' are treated as comments and skipped.
"""

import sys
import csv
import math
import statistics

# ---------- Constants ----------
SPEED_OF_LIGHT = 299702547.0      # m/s in air at sea level
DW_TIME_UNITS  = 15.65e-12        # seconds per DW1000 tick
DW_TICKS_PER_NS = 1.0 / (DW_TIME_UNITS * 1e9)  # ~63.9 ticks/ns


def load_csv(filename):
    """Load calibration CSV, skip comment lines."""
    rows = []
    metadata = {}

    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            # Parse metadata from comment lines
            if line.startswith('#'):
                if ':' in line:
                    key, _, val = line[1:].strip().partition(':')
                    metadata[key.strip()] = val.strip()
                continue

            # Skip header
            if line.startswith('sample,'):
                continue

            parts = line.split(',')
            if len(parts) < 9:
                continue

            try:
                row = {
                    'sample':             int(parts[0]),
                    'millis':             int(parts[1]),
                    'distance_m':         float(parts[2]),
                    'round_trip_ticks':   int(parts[3]),
                    'reply_delay_ticks':  int(parts[4]),
                    'tof_ticks':          int(parts[5]),
                    'rx_power_dBm':       float(parts[6]),
                    'fp_power_dBm':       float(parts[7]),
                    'quality':            float(parts[8]),
                }
                if len(parts) >= 11:
                    row['temp_C']        = float(parts[9])
                    row['pressure_hPa']  = float(parts[10])
                rows.append(row)
            except (ValueError, IndexError):
                continue

    return rows, metadata


def compute_antenna_delay(rows, known_distance_m, current_delay_reg=0):
    """
    Compute the antenna delay correction from raw TWR data.

    With antenna delay registers set to zero (or any known value),
    the measured distance includes the aggregate antenna delay
    of both devices:

        d_measured = d_true + (AD_initiator + AD_responder) * c / 2

    Wait — more precisely, in SS-TWR:
        ToF_measured = ToF_true + AD_TX_init + AD_RX_resp + AD_TX_resp + AD_RX_init
                     = ToF_true + AD_aggregate

    The DW1000 antenna delay register subtracts from TX timestamps
    and adds to RX timestamps, so setting the register corrects
    for this. The aggregate delay is split evenly between two
    identical DWM1000 modules.

    With registers at zero:
        d_measured = ToF_measured * c
        error = d_measured - d_true
        AD_aggregate = error / c  (in seconds)
        AD_per_device = AD_aggregate / 2
        register_value = AD_per_device / DW_TIME_UNITS
    """
    distances = [r['distance_m'] for r in rows]
    tof_ticks = [r['tof_ticks'] for r in rows]
    round_trips = [r['round_trip_ticks'] for r in rows]
    reply_delays = [r['reply_delay_ticks'] for r in rows]

    n = len(distances)
    mean_dist = statistics.mean(distances)
    median_dist = statistics.median(distances)
    stdev_dist = statistics.stdev(distances) if n > 1 else 0.0

    mean_tof_ticks = statistics.mean(tof_ticks)
    mean_rt = statistics.mean(round_trips)
    mean_rd = statistics.mean(reply_delays)

    # --- Outlier rejection (3-sigma) ---
    if stdev_dist > 0:
        filtered = [d for d in distances if abs(d - mean_dist) < 3 * stdev_dist]
        n_rejected = n - len(filtered)
        if filtered:
            mean_dist_filtered = statistics.mean(filtered)
            stdev_filtered = statistics.stdev(filtered) if len(filtered) > 1 else 0.0
        else:
            mean_dist_filtered = mean_dist
            stdev_filtered = stdev_dist
            n_rejected = 0
    else:
        mean_dist_filtered = mean_dist
        stdev_filtered = 0.0
        n_rejected = 0

    # --- Compute correction ---
    error_m = mean_dist_filtered - known_distance_m

    # Aggregate antenna delay (both devices combined)
    ad_aggregate_sec = error_m / SPEED_OF_LIGHT
    ad_aggregate_ns  = ad_aggregate_sec * 1e9
    ad_aggregate_ticks = ad_aggregate_sec / DW_TIME_UNITS

    # Per-device (assuming identical DWM1000 modules)
    ad_per_device_sec   = ad_aggregate_sec / 2.0
    ad_per_device_ns    = ad_per_device_sec * 1e9
    ad_per_device_ticks = ad_aggregate_ticks / 2.0

    # Register value (16-bit unsigned, each LSB = 15.65 ps)
    reg_per_device = int(round(ad_per_device_ticks)) + current_delay_reg

    # Clamp to valid range
    reg_per_device = max(0, min(65535, reg_per_device))

    # Temperature data
    temps = [r.get('temp_C', 0) for r in rows if r.get('temp_C', 0) != 0]
    temp_start = temps[0] if temps else 0
    temp_end = temps[-1] if temps else 0
    temp_drift = temp_end - temp_start if temps else 0

    return {
        'n_total':              n,
        'n_rejected':           n_rejected,
        'n_used':               n - n_rejected,
        'mean_distance':        mean_dist_filtered,
        'median_distance':      median_dist,
        'stdev_distance':       stdev_filtered,
        'known_distance':       known_distance_m,
        'error_m':              error_m,
        'ad_aggregate_ns':      ad_aggregate_ns,
        'ad_aggregate_ticks':   ad_aggregate_ticks,
        'ad_per_device_ns':     ad_per_device_ns,
        'ad_per_device_ticks':  ad_per_device_ticks,
        'reg_per_device':       reg_per_device,
        'mean_tof_ticks':       mean_tof_ticks,
        'mean_round_trip':      mean_rt,
        'mean_reply_delay':     mean_rd,
        'temp_start':           temp_start,
        'temp_end':             temp_end,
        'temp_drift':           temp_drift,
    }


def print_report(result, metadata):
    """Print a human-readable calibration report."""
    print()
    print("=" * 60)
    print("  DWM1000 ANTENNA DELAY CALIBRATION REPORT")
    print("=" * 60)

    if metadata:
        print()
        for k, v in metadata.items():
            print(f"  {k}: {v}")

    print()
    print(f"  Samples collected : {result['n_total']}")
    print(f"  Outliers rejected : {result['n_rejected']} (3-sigma)")
    print(f"  Samples used      : {result['n_used']}")
    print()
    print(f"  Known distance    : {result['known_distance']:.4f} m")
    print(f"  Mean measured     : {result['mean_distance']:.4f} m")
    print(f"  Median measured   : {result['median_distance']:.4f} m")
    print(f"  Std deviation     : {result['stdev_distance']:.4f} m")
    print(f"  Error             : {result['error_m']:+.4f} m")
    print()
    print("  --- Raw Timing (DW1000 ticks) ---")
    print(f"  Mean round trip   : {result['mean_round_trip']:.1f}")
    print(f"  Mean reply delay  : {result['mean_reply_delay']:.1f}")
    print(f"  Mean ToF          : {result['mean_tof_ticks']:.1f}")
    print()
    print("  --- Antenna Delay Correction ---")
    print(f"  Aggregate (both)  : {result['ad_aggregate_ns']:.3f} ns "
          f"({result['ad_aggregate_ticks']:.1f} ticks)")
    print(f"  Per device        : {result['ad_per_device_ns']:.3f} ns "
          f"({result['ad_per_device_ticks']:.1f} ticks)")
    print()
    print(f"  ┌─────────────────────────────────────────────┐")
    print(f"  │  RECOMMENDED REGISTER VALUE: {result['reg_per_device']:>5d}            │")
    print(f"  │  (Set on BOTH initiator and responder)      │")
    print(f"  │                                             │")
    print(f"  │  In Serial Monitor, type:                   │")
    print(f"  │    delay {result['reg_per_device']}                             │")
    print(f"  │  Then 'start' to verify.                    │")
    print(f"  └─────────────────────────────────────────────┘")
    print()

    if result['temp_drift'] != 0:
        print(f"  Temperature drift : {result['temp_drift']:+.2f} °C during collection")
        thermal_error = abs(result['temp_drift']) * 2.15  # mm per °C per device
        print(f"  Est. thermal error: ±{thermal_error:.1f} mm (2.15 mm/°C/device)")
        print()

    # Validation check
    if result['stdev_distance'] > 0.10:
        print("  ⚠ WARNING: Standard deviation > 10 cm.")
        print("    Check for multipath (nearby metal), antenna orientation,")
        print("    or unstable power supply.")
        print()

    if abs(result['error_m']) < 0.01:
        print("  ✓ Current calibration looks good (error < 1 cm).")
    elif abs(result['error_m']) > 100:
        print("  ⚠ Very large error — this is expected when registers are at zero.")
        print("    Apply the recommended value and re-run to verify.")

    print()
    print("  --- Next Steps ---")
    print(f"  1. On BOTH devices, set: delay {result['reg_per_device']}")
    print(f"  2. Run 'start' again on the initiator")
    print(f"  3. Verify mean distance ≈ {result['known_distance']:.3f} m")
    print(f"  4. If error > ±1 cm, fine-tune with ±10 on the register")
    print(f"  5. Once satisfied, note the value for production firmware")
    print()
    print(f"  For your tag/anchor firmware (tag_T1.ino, anchor_A1.ino):")
    print(f"    Add after DW1000.commitConfiguration():")
    print(f"      setAntennaDelay({result['reg_per_device']});")
    print()
    print("=" * 60)


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 cal_postprocess.py <calibration_data.csv> [known_distance_m]")
        print()
        print("  calibration_data.csv : CSV from cal_initiator serial output")
        print("  known_distance_m     : actual measured distance (default: 1.0)")
        sys.exit(1)

    filename = sys.argv[1]
    known_dist = float(sys.argv[2]) if len(sys.argv) > 2 else 1.0

    print(f"Loading: {filename}")
    print(f"Known distance: {known_dist} m")

    rows, metadata = load_csv(filename)
    if not rows:
        print("ERROR: No valid data rows found.")
        sys.exit(1)

    print(f"Loaded {len(rows)} samples.")

    # Check if metadata has a known distance
    if 'Known distance' in metadata:
        try:
            meta_dist = float(metadata['Known distance'].split()[0])
            if known_dist == 1.0 and meta_dist != 1.0:
                known_dist = meta_dist
                print(f"Using distance from file metadata: {known_dist} m")
        except ValueError:
            pass

    # Check if metadata has current delay setting
    current_delay = 0
    if 'Antenna delay register' in metadata:
        try:
            current_delay = int(metadata['Antenna delay register'])
        except ValueError:
            pass

    result = compute_antenna_delay(rows, known_dist, current_delay)
    print_report(result, metadata)


if __name__ == '__main__':
    main()
